/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import classe.Produit;
import classe.Vente;
import dao.ProduitDao;
import dao.VenteDao;
import dao.connectdb;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chadowaker
 */
public class VenteProduit extends javax.swing.JFrame {

    /**
     * Creates new form VenteProduit
     */
    public VenteProduit() {
        initComponents();
         this.setLocationRelativeTo(null);
        selectprod();
        lister();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cds = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        pv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sts = new javax.swing.JTextField();
        Ajouter = new javax.swing.JButton();
        Ajouter1 = new javax.swing.JButton();
        Retour = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        maitre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code_Produit", "Designation", "Prix", "Stock"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Code_Produit");

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Designation");

        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prix par metre");

        pv.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stock_Sorties");

        sts.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        Ajouter.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Ajouter.setForeground(new java.awt.Color(0, 102, 102));
        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        Ajouter1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Ajouter1.setForeground(new java.awt.Color(0, 102, 102));
        Ajouter1.setText("Supprimer");
        Ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajouter1ActionPerformed(evt);
            }
        });

        Retour.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Retour.setForeground(new java.awt.Color(0, 102, 102));
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        Modifier.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Modifier.setForeground(new java.awt.Color(0, 102, 102));
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Code_Produit", "Designation", "Prix Par Metre", "Stock_Sorties", "Nombre de metre"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        maitre.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nb Metre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pv, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addComponent(sts, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cds, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(maitre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Ajouter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(67, 67, 67)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(maitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ajouter)
                            .addComponent(Modifier))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Retour)
                            .addComponent(Ajouter1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int key = 0,stock = 0;String code,desi;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel model = ( DefaultTableModel)jTable1.getModel();
        int index = jTable1.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(index, 0).toString());
        cds.setText(model.getValueAt(index, 1).toString());
        desi = model.getValueAt(index, 2).toString();
        pv.setText(model.getValueAt(index, 3).toString());
        stock = Integer.valueOf(model.getValueAt(index, 4).toString());
       /*int id = (int) jTable1.getValueAt(index, 5);
        VenteDao dao = new VenteDao();
        Vente e = dao.recherche(id);
        if(e != null){
            cds.setText(e.getCode_produit());
            desi.setText(e.getDesignation());
            pv.setText(e.getPrix_vente());
            sts.setText(e.getStock_sortie());

        }*/
    }//GEN-LAST:event_jTable1MouseClicked

   

    // Méthode pour effectuer une vente
   /* public void vendreProduit(int idProduit, int quantite) {
        try {
            // Vérifier que le stock est suffisant
            int stockActuel = getStock(idProduit);
            if (stockActuel < quantite) {
                throw new Exception("Stock insuffisant");
            }

            // Mettre à jour le stock
            int nouveauStock = stockActuel - quantite;
            updateStock(idProduit, nouveauStock);

            // Ajouter la vente à la base de données
            PreparedStatement preparedStatement = connect.prepareStatement(
                    "INSERT INTO Vente(id_produit, quantite) VALUES (?, ?)");
            preparedStatement.setInt(1, idProduit);
            preparedStatement.setInt(2, quantite);
            preparedStatement.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
*/
    private void update(){
        try{
            int newqty = stock - Integer.valueOf(sts.getText());
            PreparedStatement pst = connect.prepareStatement("update article set stock = '"+newqty+"' where id ="+cds.getText());
            pst.executeUpdate();
            connect.close();
        }catch(Exception e){
            
        }
    }
    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        String desi = combo.getSelectedItem().toString();
        String sql = "select * from article where designation ='"+desi+"'";
        try {
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                cds.setText(rs.getString("code_produit"));

            }
        }catch(SQLException ex){
            Logger.getLogger(VenteProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboItemStateChanged

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        VenteDao dao = new VenteDao();
        String code = cds.getText();
        String designation = combo.getSelectedItem().toString();
        String prix = pv.getText();
        String stock = sts.getText();
        String metre = maitre.getText();

        if (designation.equals("") || prix.equals("")|| stock.equals("")){
            JOptionPane.showMessageDialog(this, "RENSEIGNER LES CHAMPS SVP");
        }else{
		String sql="update article set stock = stock-'"+stock+"' where code_produit='"+code+"'"; 
                try{
                    Vente v = new Vente(code,designation,prix,stock,metre);
                    dao.ajouter(v);
                //reduction automatique du nombre d'un produit lors d'une vente:
                    Statement st = this.connect.createStatement();
                    st.executeUpdate(sql);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null," Echec ajout !",null,JOptionPane.ERROR_MESSAGE);
                }
                vider();
                lister();
                update();
                
               
            } 
            
    }//GEN-LAST:event_AjouterActionPerformed

    private void Ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajouter1ActionPerformed
        VenteDao dao = new VenteDao();
        String code = cds.getText();
        String designation = combo.getSelectedItem().toString();
        String prix = pv.getText();
        String stock = sts.getText();
        String metre = maitre.getText();
        int id = jTable2.getSelectedRow();
        int select = (int) jTable2.getValueAt(id, 0);
        Vente v = new Vente(code,designation,prix,stock,metre);
        dao.supprimer(select);
        vider();
        lister();
    }//GEN-LAST:event_Ajouter1ActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Acceuil A = new Acceuil();
        A.setVisible(true);
        this.hide();
    }//GEN-LAST:event_RetourActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        VenteDao dao = new VenteDao();
        String code = cds.getText();
        String designation = combo.getSelectedItem().toString();
        String prix = pv.getText();
        String stock = sts.getText();
       String metre = maitre.getText();
        int id = jTable2.getSelectedRow();
        int select = (int) jTable2.getValueAt(id, 0);
        Vente v = new Vente(code,designation,prix,stock,metre);
        dao.modifier(v,select);
        vider();
        lister();
    }//GEN-LAST:event_ModifierActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int index = jTable2.getSelectedRow();
        int id = (int) jTable2.getValueAt(index, 0);
        VenteDao dao = new VenteDao();
        Vente e = dao.recherche(id);
        if(e != null){
            cds.setText(e.getCode_produit());
            combo.setSelectedItem(e.getDesignation());
            pv.setText(e.getPrix_vente());
            sts.setText(e.getStock_sortie());
            maitre.setText(e.getMaitre());
        }
    }//GEN-LAST:event_jTable2MouseClicked

     //Liste
    private void selectprod() {
        ProduitDao dao = new ProduitDao();
        List<Produit> e = new ArrayList();
        e = dao.liste();
        for (int i = 0; i < e.size(); i++) {
            ((DefaultTableModel) jTable1.getModel()).addRow(new Object[]{
                e.get(i).getId(),
                e.get(i).getCode_produit(),
                e.get(i).getDesignation(),
                e.get(i).getPrix(),
                e.get(i).getStock()
               
                });

        }
    }
    public Connection connect = connectdb.getInstance();
     public void fillCombo(){
       String sql = "select * from article";
       try{
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                combo.addItem(rs.getString("designation"));
               
            }
       }catch(SQLException ex){
            Logger.getLogger(VenteProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     
     //Liste produc
    private void lister() {
        VenteDao dao = new VenteDao();
        List<Vente> v = new ArrayList();
        v = dao.liste();
        for (int i = 0; i < v.size(); i++) {
            ((DefaultTableModel) jTable2.getModel()).addRow(new Object[]{
                v.get(i).getId(),
                v.get(i).getCode_produit(),
                v.get(i).getDesignation(),
                v.get(i).getPrix_vente(),
                v.get(i).getStock_sortie(),
               v.get(i).getMaitre()
                });

        }
    }
    
    
    private void vider() {
        cds.setText("");
        combo.setSelectedItem("");
        pv.setText("");
        sts.setText("");
        maitre.setText("");
        

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int nbr_ligne = model.getRowCount();
        for (int i = nbr_ligne - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    int old, now;
    public void def(){
        try {
            String code = cds.getText();
            String sql = "select * from article where code_produit ="+code+"";
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                old = rs.getInt("stock");
            }
            int dec = Integer.parseInt(sts.getText());
            now = old - dec;
            System.out.println(now);
            String nvstock = Integer.toString(now);
            String req = "update article set stock ='"+now+"' where code_produit ="+code;
            Statement st = connect.createStatement();
            st.executeUpdate(req);
            selectprod();
        } catch (SQLException ex) {
            Logger.getLogger(VenteProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenteProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenteProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenteProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenteProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenteProduit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Ajouter1;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Retour;
    private javax.swing.JTextField cds;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField maitre;
    private javax.swing.JTextField pv;
    private javax.swing.JTextField sts;
    // End of variables declaration//GEN-END:variables
}
